server:
  port: 8080
spring:
  datasource:
    url: jdbc:hsqldb:hsql:/localhost:9001/db
    driverClassName: org.hsqldb.jdbcDriver
    username: root
    password: pass
  jpa:
    show-sql: true
    open-in-view: false
iyzico:
  api-key: sandbox-2lcnB40RFsVV2cgasdhRdabezlyJg8n5
  secret-key: sandbox-Xg5yIfWYH8f7fiBXcZ0JrxLmOV5awr6O
  base-url: https://sandbox-api.iyzipay.com/